import { IconDefinition } from './types'
// 作成した定数ファイルをインポートしてください
import { VFD_COLORS } from '@/lib/constants' 

const basePath = process.env.NODE_ENV === 'production' ? '/d919' : ''

export const CUSTOM_ICONS: IconDefinition[] = [
  {
    id: 'mp3-logo',
    name: 'MP3',
    type: 'IMAGE', 
    maskSrc: `${basePath}/images/masks/mp3.svg`, 
    activeModes: ['UPLOAD_PROMPT', 'PEAK_HOLD', 'ANIMATION', 'MUSIC'],
    condition: () => true, 
    x: 326,
    y: 89.6,
    width: 100, 
    height: 16.7,
    color: VFD_COLORS.RED 
  },
  {
    id: 'mp3-guide',
    name: 'MP3GUIDE',
    type: 'IMAGE', 
    maskSrc: `${basePath}/images/masks/mp3-guide.svg`, 
    activeModes: ['UPLOAD_PROMPT', 'PEAK_HOLD', 'ANIMATION', 'MUSIC'],
    condition: () => true, 
    x: 312.5,
    y: 22.7,
    width: 233, 
    height: 150,
    color: VFD_COLORS.GREEN 
  },
  {
    id: 'balance-center',
    name: 'CENTER',
    type: 'IMAGE', 
    maskSrc: `${basePath}/images/masks/balance-center.svg`, 
    activeModes: ['UPLOAD_PROMPT', 'PEAK_HOLD', 'ANIMATION', 'MUSIC'],
    condition: () => true, 
    x: 1257,
    y: 270,
    width: 233, 
    height: 9.1,
    color: VFD_COLORS.RED 
  },
  {
    id: 'balance-guide',
    name: 'BALANCEGUIDE',
    type: 'IMAGE', 
    maskSrc: `${basePath}/images/masks/balance-guide.svg`, 
    activeModes: ['UPLOAD_PROMPT', 'PEAK_HOLD', 'ANIMATION', 'MUSIC'],
    condition: () => true, 
    x: 1244,
    y: 184,
    width: 233, 
    height: 157,
    color: VFD_COLORS.GREEN 
  },
  {
    id: 'balance-seat',
    name: 'BALANCESEAT',
    type: 'IMAGE', 
    maskSrc: `${basePath}/images/masks/balance-seat.svg`, 
    activeModes: ['UPLOAD_PROMPT', 'PEAK_HOLD', 'ANIMATION', 'MUSIC'],
    condition: () => true, 
    x: 1250,
    y: 244,
    width: 233, 
    height: 73,
    color: VFD_COLORS.GREEN 
  },
  {
    id: 'cd-circle',
    name: 'CDCIRCLE',
    type: 'IMAGE', 
    maskSrc: `${basePath}/images/masks/cd-circle.svg`, 
    activeModes: ['UPLOAD_PROMPT', 'PEAK_HOLD', 'ANIMATION', 'MUSIC'],
    condition: () => true, 
    x: 21,
    y: 180,
    width: 233, 
    height: 80,
    color: VFD_COLORS.GREEN 
  },
  {
    id: 'cd-in',
    name: 'CDIN',
    type: 'IMAGE', 
    maskSrc: `${basePath}/images/masks/cd-in.svg`, 
    activeModes: ['UPLOAD_PROMPT', 'PEAK_HOLD', 'ANIMATION', 'MUSIC'],
    condition: () => true, 
    x: 1262,
    y: 85,
    width: 233, 
    height: 43,
    color: VFD_COLORS.RED 
  },
  {
    id: 'corner-ring',
    name: 'CORNERRING',
    type: 'IMAGE', 
    maskSrc: `${basePath}/images/masks/corner-ring.svg`, 
    activeModes: ['UPLOAD_PROMPT', 'PEAK_HOLD', 'ANIMATION', 'MUSIC'],
    condition: () => true, 
    x: -85,
    y: 310,
    width: 233, 
    height: 28,
    color: VFD_COLORS.GREEN 
  },
  {
    id: 'corner',
    name: 'CORNER',
    type: 'IMAGE', 
    maskSrc: `${basePath}/images/masks/corner.svg`, 
    activeModes: ['UPLOAD_PROMPT', 'PEAK_HOLD', 'ANIMATION', 'MUSIC'],
    condition: () => true, 
    x: -64,
    y: 262,
    width: 233, 
    height: 78.2,
    color: VFD_COLORS.BLUE,
  },
  {
    id: 'folder',
    name: 'FOLDER',
    type: 'IMAGE', 
    maskSrc: `${basePath}/images/masks/folder.svg`, 
    activeModes: ['UPLOAD_PROMPT', 'PEAK_HOLD', 'ANIMATION', 'MUSIC'],
    condition: () => true, 
    x: 317,
    y: 72,
    width: 233, 
    height: 60,
    color: VFD_COLORS.CYAN
  },
  {
    id: 'folder-in',
    name: 'FOLDERIN',
    type: 'IMAGE', 
    maskSrc: `${basePath}/images/masks/folder-in.svg`, 
    activeModes: ['UPLOAD_PROMPT', 'PEAK_HOLD', 'ANIMATION', 'MUSIC'],
    condition: () => true, 
    x: 313,
    y: 81,
    width: 233, 
    height: 40,
    color: VFD_COLORS.BLUE,
  },
  {
    id: 'note-1',
    name: 'NOTE1',
    type: 'IMAGE', 
    maskSrc: `${basePath}/images/masks/note-1.svg`, 
    activeModes: ['UPLOAD_PROMPT', 'PEAK_HOLD', 'ANIMATION', 'MUSIC'],
    condition: () => true, 
    x: 391,
    y: 63.5,
    width: 233, 
    height: 34,
    color: VFD_COLORS.CYAN,
  },
  {
    id: 'note-2',
    name: 'NOTE2',
    type: 'IMAGE', 
    maskSrc: `${basePath}/images/masks/note-2.svg`, 
    activeModes: ['UPLOAD_PROMPT', 'PEAK_HOLD', 'ANIMATION', 'MUSIC'],
    condition: () => true, 
    x: 359,
    y: 68,
    width: 233, 
    height: 34,
    color: VFD_COLORS.CYAN,
  },
  {
    id: 'note-3',
    name: 'NOTE3',
    type: 'IMAGE', 
    maskSrc: `${basePath}/images/masks/note-3.svg`, 
    activeModes: ['UPLOAD_PROMPT', 'PEAK_HOLD', 'ANIMATION', 'MUSIC'],
    condition: () => true, 
    x: 356,
    y: 97,
    width: 233, 
    height: 34,
    color: VFD_COLORS.CYAN,
  },
  {
    id: 'note-ring',
    name: 'NOTERING',
    type: 'IMAGE', 
    maskSrc: `${basePath}/images/masks/note-ring.svg`, 
    activeModes: ['UPLOAD_PROMPT', 'PEAK_HOLD', 'ANIMATION', 'MUSIC'],
    condition: () => true, 
    x: 371,
    y: 62,
    width: 233, 
    height: 62,
    color: VFD_COLORS.BLUE,
  },
  {
    id: 'posi',
    name: 'POSI',
    type: 'IMAGE', 
    maskSrc: `${basePath}/images/masks/posi.svg`, 
    activeModes: ['UPLOAD_PROMPT', 'PEAK_HOLD', 'ANIMATION', 'MUSIC'],
    condition: () => true, 
    x: 1257,
    y: 322,
    width: 233, 
    height: 18,
    color: VFD_COLORS.RED,
  },
  {
    id: 'sa',
    name: 'SA',
    type: 'IMAGE', 
    maskSrc: `${basePath}/images/masks/sa.svg`, 
    activeModes: ['UPLOAD_PROMPT', 'PEAK_HOLD', 'ANIMATION', 'MUSIC'],
    condition: () => true, 
    x: 204,
    y: 61,
    width: 233, 
    height: 21,
    color: VFD_COLORS.CYAN,
  },
  {
    id: 'cd',
    name: 'CD',
    type: 'IMAGE', 
    maskSrc: `${basePath}/images/masks/cd.svg`, 
    activeModes: ['UPLOAD_PROMPT', 'PEAK_HOLD', 'ANIMATION', 'MUSIC'],
    condition: () => true, 
    x: 11,
    y: 195,
    width: 233, 
    height: 22,
    color: VFD_COLORS.CYAN,
  },
  {
    id: 'rom',
    name: 'ROM',
    type: 'IMAGE', 
    maskSrc: `${basePath}/images/masks/rom.svg`, 
    activeModes: ['UPLOAD_PROMPT', 'PEAK_HOLD', 'ANIMATION', 'MUSIC'],
    condition: () => true, 
    x: 22,
    y: 201,
    width: 233, 
    height: 45,
    color: VFD_COLORS.CYAN,
  },
]